### ISSUE TITLE
"Mapping values are not allowed in this context" Yaml error

### ISSUE THREAD

**Issue by Lospi** [JayJay1989/TwitchLib.ExampleBot#1]
config.yaml file returns error with all parameters:

[config.txt](https://github.com/JayJay1989/TwitchLib.ExampleBot/files/4151348/config.txt)

(Posting as .txt and image since Markdown breaks code display)
![yaml file1](https://user-images.githubusercontent.com/20178351/73712767-e914cc00-46e9-11ea-80b0-450fcecd9038.png)
![yaml file](https://user-images.githubusercontent.com/20178351/73712913-56286180-46ea-11ea-96a0-23364c7042fb.png)

**Comment by JayJay1989** [comment]
What you can try:
- don't use space after `oauth:`
- fill in `telegram_secret_key` and `pubsub` with some random text

**Comment by Lospi** [comment]
It works now! Thanks!

But still, even though I'm online on Twitch, it doesn't show me as 'online'
